name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "yarn install --frozen-lockfile"
        run: yarn install --frozen-lockfile

      - name: "yarn run semantic-release"
        run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
